source 'https://github.com/CocoaPods/Specs.git'

target 'TimerScroll', :exclusive => true do
  pod "TimerScroll", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TimerScroll", :path => "../"

  
end
