source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'TimerScroll', :exclusive => true do
  
  pod 'TFQImageScrollView', :git => 'https://github.com/tanfq1989/TFQImageScrollView.git'
  pod "TimerScroll", :path => "../"
  pod "SDWebImage"
end

target 'Tests', :exclusive => true do
  pod "TimerScroll", :path => "../"

  
end
